- name: apt terminal packates
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tmux
    - tmuxinator

- name: add tmux config
  copy:
    src: tmux.config
    dest: '{{ user_config }}/.tmux.conf'


- name: Create symbolic link
  file:
   src: '{{ user_config }}/.tmux.conf'
   dest: '{{ home_path }}/.tmux.conf'
   state: link
   force: yes